specifying path to .env file inside betterScripts
benoror/better-npm-run pull request #67
Opened 2017-04-19 10:47 UTC by maslennikov

2017-07-07 16:59 UTC, galenandrew requested changes
@maslennikov thank you for your PR!! 🎉 

This change makes sense to me and would be a good addition.

I left a few comments on the README explanations as well as a small change requested in the script. Also, can you add a test for using the `envpath` option to make sure it doesn't load the root-level `.env` file?

2017-07-07 16:59 UTC, galenandrew commented on lib/exec.js
> +  script = (typeof script === 'string' ? {command: script} : script)
It is preferred to assign a new variable here instead of reassigning a passed argument.

2017-07-07 16:59 UTC, galenandrew commented on README.md
> +If you have an `.env` file in your project root it will be loaded on every command. Path to the `.env` file can be further specified with the CLI argument.
Can we rephrase this addition to the following?

> _An alternate env file can be used by setting the `envpath` option (or `--path` option if using the CLI)._

2017-07-07 16:59 UTC, galenandrew commented on README.md
> +_Path to the `.env` file specified via `envpath` attribute in the `betterScripts` script definition will take precedence over default path or path passed with the CLI argument._
Let's simplify this explanation a bit…thoughts on removing the example and replacing with the below statement?

> _Environment variables defined using the `env` object in package.json will overwrite values loaded from an `.env` file. When the `envpath` option is defined in package.json, the root level env file or `--path` CLI option will not be loaded._

2017-07-31 14:26 UTC, benoror commented
Hey @maslennikov ! any updates regarding this PR?

2020-04-14 23:27 UTC, closed without merging